TRUNCATE TABLE T_SIMILITARY_METHODS
/--split
DROP TABLE T_SIMILITARY_METHODS
/--split
DROP INDEX IDX_COLLECTION
/--split
TRUNCATE TABLE T_DATA_VECTOR
/--split
DROP TABLE T_DATA_VECTOR CASCADE CONSTRAINTS
/--split
TRUNCATE TABLE T_COLLECTION
/--split
DROP TABLE T_COLLECTION CASCADE CONSTRAINTS
/--split
DROP TYPE V_BINARY_DOUBLE
/--split
DROP TYPE V_VARCHAR2