-- ELIMINAR BASE TABLAS Y PAQUETES
DECLARE
    V_EXIST NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXIST FROM ALL_TABLES WHERE TABLE_NAME='T_COLLECTION';
    IF V_EXIST > 0 THEN
        EXECUTE IMMEDIATE 'drop table T_COLLECTION';    
    END IF;
    
    SELECT COUNT(*) INTO V_EXIST FROM ALL_TABLES WHERE TABLE_NAME='T_DATA_VECTOR';
    IF V_EXIST > 0 THEN
        EXECUTE IMMEDIATE 'drop table T_DATA_VECTOR';    
    END IF;
    
    SELECT COUNT(*) INTO V_EXIST FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE BODY' AND OBJECT_NAME = 'DBVECTORIAL';
    IF V_EXIST > 0 THEN
        EXECUTE IMMEDIATE 'drop package body DBVECTORIAL';
    END IF;
    
    SELECT COUNT(*) INTO V_EXIST FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE' AND OBJECT_NAME = 'DBVECTORIAL';
    IF V_EXIST > 0 THEN
        EXECUTE IMMEDIATE 'drop package DBVECTORIAL';
    END IF;
END;